### PR TITLE
Improve missing strict deps warnings

### LINKED ISSUE #705: `experimental_strict_kotlin_deps` logs `null` for the missing dep
When I use `experimental_strict_kotlin_deps = "error"` in my toolchain definition, it does appear to find strict dep violations, but it doesn't correctly log the name of the violating dep. This is with `v1.5.0`. Looks like this:
``` 
** Please add the following dependencies: null to //identities-api/src/main:main 
 ** You can use the following buildozer command: buildozer 'add deps null' //identities-api/src/main:main
```

### PR DESCRIPTION
**Pull request by lukaciko**
Makes the missing strict dependency warnings more like what they are when compiling Java code with Bazel:

- Prints the target label when that can be resolved, otherwise prints the Jar path (instead of null)
- Prints the buildozer command with the resolved target labels
- Does not print the buildozer command if no target label could be resolved

Closes #705.

## Examples

These are how the warning look for Java compilation:
```
warning: [strict] Using type com.google.common.collect.Lists from an indirect dependency (TOOL_INFO: "bazel-out/darwin_arm64-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/com/google/guava/guava/26.0-jre/header_guava-26.0-jre.jar").
        System.err.println(Lists.reverse(C.INTEGERS) + " ");
                           ^
B.java:9: warning: [strict] Using type C from an indirect dependency (TOOL_INFO: "//:sometarget wrapped in kt_jvm_library"). See command below **
        System.err.println(Lists.reverse(C.INTEGERS) + " ");
                                         ^
 ** Please add the following dependencies:
  //:sometarget to //:A
 ** You can use the following buildozer command:
buildozer 'add deps //:sometarget' //:A

```

This is how the warnings look for Kotlin compilation before the change:
```
 ** Please add the following dependencies: //:sometarget null null to //:A
 ** You can use the following buildozer command: buildozer 'add deps //:sometarget null null' //:A
```

This is how the warnings look for Kotlin compilation after the change:
```
 ** Please add the following dependencies:
//:sometarget bazel-out/darwin_arm64-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/com/google/guava/guava/26.0-jre/header_guava-26.0-jre.jar bazel-out/darwin_arm64-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/javax/inject/javax.inject/1/header_javax.inject-1.jar to //:A
 ** You can use the following buildozer command:
buildozer 'add deps //:sometarget' //:A
```

### CODE REVIEW

**Review by Bencodes — APPROVED** [review]
Do you have examples of what the various outputs look like after this change that you can attach to the PR for reference?

**Comment by lukaciko** [comment]
@Bencodes I added examples to the PR description and updated the formatting again with some extra newlines. There's plenty more to do here, but I think this is a good first step.

**Comment by restingbull** [comment]
Thanks for doing this!

**Review by Bencodes — APPROVED** [review]

**Comment by fzakaria** [comment]
Why are the labels missing and JarPaths are even used?
That part is not clear.

**Comment by lukaciko** [comment]
@fzakaria I described some of that in the issue that this PR closed. There's a few things missing, most of them outside rules_kotlin.

**Pull request merged**
