### PR TITLE
Add InteliiJ aspect info

### PR DESCRIPTION
**Pull request by szinn**
- allows the bazel-intellij aspect processing to correctly identify the version
  of Kotlin being used and update the source accordingly
- part of the fix for https://github.com/bazelbuild/intellij/issues/1274

### CODE REVIEW

**Comment by cgruber** [comment]
So this seems reasonable to me, but I'm curious about passing it as a separate part of the struct, rather than baking it in to values in KtJvmInfo. Is there a strong reason to prefer that?  Is there prior art on passing toolchains in that providers struct?  

I see examples of passing back ToolchainInfo from rules that define the toolchain, but this feels different. I'm struggling to see a good example anywhere to resolve this in my mind. This isn't a toolchain rule you're editing.

Also, do you need the stdlib compilation path? (or is that just to force the stdlibs into the IDE thingy?)  Is this not something you can attach to an aspect?  The PR description references aspects, but I don't see an aspect given here (and the intellij aspect lives elsewhere).  Could you possibly get the ctx.rule.toolchain in the intellij aspect, to get this information?

**Comment by szinn** [comment]
I was seeing that this kind of information was passed back in the toolchain as you described.  As well, the version of the tool is more a toolchain info, but could easily be passed in the KtJvmInfo as well and extracted from there.

The stdlib path was purely to fill out the intellij structure.  Perhaps it isn't needed there and just the version can be put into the KtJvmInfo.  Shall I make this change to the PR?

As well, this change does nothing for the tool, it is putting the information into the return structure so that it can be extracted by the intellij aspect code (which is the other PR I shared)

**Comment by szinn** [comment]
@cgruber This change has been updated to put the language_version in the KtJvmInfo struct.

**Comment by cgruber** [comment]
I'm just assuming this can be picked up on other side by the plugin (or its aspect).  But this change is fine, as it is, assuming something will use it.

**Comment by szinn** [comment]
I have a change for bazel-intellij to pick up this change

**Comment by cgruber** [comment]
I'll be releasing 1.3.1 this weekend or next week, I expect, so it'll be available very soon.

**Pull request merged**
