### PR TITLE
Add instructions on configuring ijwb to properly know about kotlin

### PR DESCRIPTION
**Pull request by cgruber**
Add instructions on configuring ijwb to properly know about kotlin, and mention the experimental plugins in case the current release isn't yet available.

### CODE REVIEW

**Comment by hsyed** [comment]
@brendandouglas what is the ETA on a release of the plugin with Kotlin support. This PR creates a link to a build of the plugin that we use internally.

**Comment by brendandouglas** [comment]
These kind of instructions really belong on the long-neglected docs site (ij.bazel.build).

There's another release scheduled for upload this Friday, which will be at least as recent as what's checked in here.

**Comment by hsyed** [comment]
Ok so if it's going in on Friday there's no point linking to my releases.

This is all that is the documentation that is needed Brendan. Could you update them ? 

```
additional_languages:
  kotlin
```

The Kotlin section for configuring the language version is pointless with my next bit of work (picking up kotlin config from the rules) so no need to document it -- it picks up the default from the Kotlin plugin currently.

**Comment by cgruber** [comment]
I looked at ij.bazel.build and couldn't see where this should really fit there. :/  

But I"ll close this PR, as it does seem that part of it is irrelevant, and the other part should be part of the docs for the tools in question.

**Pull request closed without merging**
