### PR TITLE
Fix jdeps collectTypeArguments stackoverflow error

### PR DESCRIPTION
**Pull request by Bencodes**
https://github.com/bazelbuild/rules_kotlin/issues/485

### CODE REVIEW

**Comment by Bencodes** [comment]
@jongerrish

**Comment by restingbull** [comment]
@jongerrish

**Comment by jongerrish** [comment]
Perfect, you could also validate it with a test see: io.bazel.kotlin.builder.tasks.jvm.KotlinBuilderJvmJdepsTest#function call parameter type nested type parameters should be an explicit dependency otherwise I'll add it later.

**Review by jongerrish — APPROVED** [review]
Thanks for the fix @Bencodes

**Review by restingbull — APPROVED** [review]

**Pull request merged**
