### PR TITLE
kt_toolchain_ide_info rule generating ide toolchain json file and res…

### PR DESCRIPTION
**Pull request by hsyed**
…tructure skylark a bit

### CODE REVIEW

**Comment by hsyed** [comment]
@buchgr this one wasn't passing. I gave the build kite system the privs it wanted (I think).

**Comment by buchgr** [comment]
It's not triggered on buildkite?

**Comment by hsyed** [comment]
@buchgr it did trigger but some test conditions failed, “must have push access to view collaborators”

[see](https://buildkite.com/bazel/kotlin-rules-kotlin-presubmit/builds?branch=hsyed%3Akt_toolchain_ide_info)

**Comment by buchgr** [comment]
@hsyed that was a permission problem. fixed!

**Pull request closed without merging**
