### PR TITLE
Revert "Isolate Kotlin compiler instances for Multiplex workers."

### PR DESCRIPTION
**Pull request by rockwotj**
Reverts bazelbuild/rules_kotlin#515

This results in targets being able to get out of date https://github.com/bazelbuild/rules_kotlin/issues/531

I'm assuming that this was enabled due to the work around from https://youtrack.jetbrains.com/issue/KT-45007 @jongerrish? Which seems to be fixed in kotlin 1.5... Or maybe we should only enable this system property for multiplexing mode? I wasn't able to easily figure out how to do this, so I figured that reverting this change until then was a better solution

### CODE REVIEW

**Comment by restingbull** [comment]
*sigh* Willing to bet that this is due to the kotlin compiler not checking content hash but date stamp.

We can't completely revert this change, as the initial fix dealt with cross contamination. Thanks for the debugging!
Going to need to sort out what is happening.

**Comment by rockwotj** [comment]
The cross contamination was only for experimental_multiplex_workers right? It seems undesirable to break the defaults to make an experimental feature work.

**Comment by rockwotj** [comment]
Also I found one place in kotlinc where it caches based on timestamp and file length for zip files, and a couple other places that just looked at timestamps. I'll comment on the bug where I found those caches in kotlinc

**Comment by restingbull** [comment]
Wait... I was under the impression this issue only cropped up with multiplex workers enabled?

**Comment by rockwotj** [comment]
@restingbull sorry to not be clear, but this repros with just the default settings (no experimental flags on) with the latest release.

**Comment by rockwotj** [comment]
You can test if you want by following my steps in https://github.com/bazelbuild/rules_kotlin/issues/531#issuecomment-882654313

**Review by restingbull — APPROVED** [review]

**Pull request merged**
