### PR TITLE
Generic -Xopt-in support

### PR DESCRIPTION
**Pull request by sugarmanz**
Inspired from conversation on #653 to solve for #603.

I'm only opening this PR because this is a feature I needed today and haven't seen any movement on #653 in almost a month. Feel free to disregard if this PR is redundant pending work from #653. 

If necessary, I can add to some of the other `opts.bzl` files, but it wasn't clear to me the resolution of this comment since the PR was approved afterwards:
https://github.com/bazelbuild/rules_kotlin/pull/653#issuecomment-1010326401

### CODE REVIEW

**Review by restingbull — APPROVED** [review]

**Comment by restingbull** [comment]
TODO: Resolve conflicts.

**Review by nkoroste — APPROVED** [review]
LGTM

**Review by Bencodes — APPROVED** [review]
Lgtm. Tested this one against our repo as well. Thanks for the PR!

**Comment by xaka** [comment]
Is it possible to backport this change to 1.5.x branch and make another release while 1.6 is still in progress?

**Comment by brettwooldridge** [comment]
I think it would be great to see smaller but more frequent releases. The cadance in the past has been 6mos-1yr between releases. In my opinion, it would be better to have a release every 2-3 months with whatever changes and fixes have been made during that period. In addition to benefiting end-users, I feel like this would also generate more activity on the project itself.

It feels like there are enough improvements in just in the past 2 months to justify a 1.6.0 release.

What do you guys think?

**Pull request merged**
