### PR TITLE
Add support for Kotlin coverage

### PR DESCRIPTION
**Pull request by jongerrish**
Fixes: #300

### CODE REVIEW

**Review by nkoroste — APPROVED** [review]

**Review by restingbull — APPROVED** [review]

**Comment by tokudu** [comment]
Epic!

**Comment by sgammon** [comment]
thank you! i could never quite get this over the line

**Comment by xzhang-brex** [comment]
thank you! could you explain how should we utilize this change? basically im trying to make the code coverage work for IntelliJ

**Comment by bhushan-helloFresh** [comment]
> thank you! could you explain how should we utilize this change? basically im trying to make the code coverage work for IntelliJ

Were you able to generate the code coverage for kotlin apps.

**Pull request merged**
