### PR TITLE
Kotlin 1.5 support

### PR DESCRIPTION
**Pull request by Bencodes**
This PR includes:
- Support for Kotlin 1.5.x API and language levels
- Compiles `rules_kotlin` using 1.5.10
- Updates `validate_kotlinc_options` to fail fast when the new IR Kotlinc compiler flags that are enabled by default in 1.5 are passed in.

### CODE REVIEW

**Comment by Bencodes** [comment]
We are testing this in our repository and will report back.

**Comment by Bencodes** [comment]
It would be great to get this merged first so that we can be sure that there are no compose related regressions https://github.com/bazelbuild/rules_kotlin/pull/493

**Comment by Bencodes** [comment]
We encountered this in our repository while testing 1.5.x https://github.com/bazelbuild/bazel/issues/13553

**Comment by nkoroste** [comment]
Another issue we found https://github.com/bazelbuild/rules_kotlin/issues/549

**Comment by Bencodes** [comment]
> Another issue we found #549

@alexjlockwood also ran into something similar in a few of our targets.

**Comment by jeffzoch** [comment]
@Bencodes is bazelbuild/bazel#13553 blocking?

**Comment by Bencodes** [comment]
@jeffzoch we found a way to work around that issue inside our codebase so probably not a blocker.

**Comment by nkoroste** [comment]
@Bencodes Can you please describe what you did for your workaround?

**Comment by Bencodes** [comment]
@nkoroste The workaround is documented in the `bazel_issue_13553`  repo that I created for the bug report https://github.com/Bencodes/bazel_issue_13553/pull/1

**Comment by cgruber** [comment]
As an FYI, I want to merge this, but I'm going to do a thing where I extract a copy of the builder and set it up separately as a 1.4-specific builder, then merge this in. @restingbull and I realized we are going to have to start segmenting the tooling so that we handle different kotlin versions a bit differently (initially with a big fat dupe with minor tweaks, later refactored into smaller deltas). But I'll merge this in, I just need to yoink out the other, first. (and then I'll have some hassle, probably, messing with 3rd party deps. Sigh).

**Comment by Kernald** [comment]
@Bencodes this can probably be closed now that #577 has been merged?

**Pull request closed without merging**
