### PR TITLE
Update the current RC release

### PR DESCRIPTION
**Pull request by Bencodes**

### CODE REVIEW

**Comment by rockwotj** [comment]
Have y'all considered using something like https://shields.io/category/version to automate this?

**Comment by Bencodes** [comment]
> Have y'all considered using something like https://shields.io/category/version to automate this?
> 
> EDIT: 
> 
> 
> 
> Examples
> 
> 
> 
> latest stable release
> 
> 
> 
> latest rc

Great call out to future proof this. I'll merge it if you open a PR!

**Comment by arunkumar9t2** [comment]
@Bencodes I took a shot at this here https://github.com/bazelbuild/rules_kotlin/pull/799

**Comment by restingbull** [comment]
https://github.com/bazelbuild/rules_kotlin/pull/799 fixes this more permanently.

**Pull request closed without merging**
