### PR TITLE
Parallelize multiplex work execution

### PR DESCRIPTION
**Pull request by jdai8**
Fixes https://github.com/bazelbuild/rules_kotlin/issues/494.

See the Java compilation implementation: https://github.com/bazelbuild/bazel/blob/d61d394107f46ad27509b339741a45f4c7205965/src/main/java/com/google/devtools/build/lib/worker/WorkRequestHandler.java#L77

### CODE REVIEW

**Comment by jdai8** [comment]
cc: @jongerrish

**Comment by jongerrish** [comment]
Thanks for the fix Jack, just testing this out on our repo now.

**Comment by jongerrish** [comment]
I ran a suite of incremental change tests on our repo and saw that performance for each one is at least as good as without multiplex workers enabled. Some targets which trigger a lot of Kotlin actions show pretty significant performance improvements, up to 20% in some cases! Thanks for the quick fix!

**Comment by restingbull** [comment]
I fixed the coroutine usage in https://github.com/bazelbuild/rules_kotlin/pull/496

Thank you for the bugfix and issue!

**Comment by restingbull** [comment]
(My preference is to use coroutines for the moment -- until the profiler tells me it's a bad idea.)

**Pull request closed without merging**
