### PR TITLE
Support for Kotlin 1.3

### PR DESCRIPTION
**Pull request by AlexeySoshin**
Ruleset for Kotlin 1.3 used @Wix 

Inspired by https://github.com/cgruber/rules_kotlin
@cgruber

### CODE REVIEW

**Comment by AlexeySoshin** [comment]
I signed it!

**Comment by cgruber** [comment]
I'm glad you took inspiration, but the reason I'm keeping it in my fork, and haven't filed more or less this PR, is that the team has indicated that they're not going to take patches to the legacy rules, until they've published the new rules according to the roadmap.  So I just haven't bugged the team with PRs like this, because they're super busy trying to get the new rules out, and there's less friction just maintaining my fork. 🤷‍♂

**Comment by cgruber** [comment]
@jin - has that position changed?

**Comment by AlexeySoshin** [comment]
@cgruber Glad you didn't keep it private. Figuring what the hell is wrong with Kapt would be a nightmare by myself :)

**Comment by cgruber** [comment]
Some of it is pretty arcane, it's true.

**Comment by jin** [comment]
As mentioned in https://github.com/bazelbuild/rules_kotlin/issues/159#issuecomment-532809960, we'll be working with @cgruber to merge his fork to this repo. 

Thank you @AlexeySoshin for creating this PR!

**Pull request closed without merging**
